### ISSUE TITLE
Reconstruct ACLs on Entries

### ISSUE THREAD

**Issue by tabledevil** [janstarke/ntdsextract2#7]
Would it be possible to reconstruct the ACLs (DACL) of entries so that you could check for possibly hidden Accounts?
(https://www.semperis.com/blog/find-hidden-active-directory-objects/)

**Comment by janstarke** [comment]
at least it's an interesting question. I' take a look

**Comment by janstarke** [comment]
I started working on this issue, with the following progress for now:

- implemented a crate to parse security descriptors (https://github.com/janstarke/sddl)
- created a simple implementation to access the `sd_table`

Now I'm stuck because the security descriptor is stored as `Long`, which is currently not supported by [`libesedb`](https://github.com/sunsetkookaburra/rust-libesedb). I need to take a look at it...
